import DocCMiddleware
import Vapor

// configures your application
public func configure(_ app: Application) throws {
    // We do not need to enable FileMiddleware as we're not serving the files directly.
    // In a typical use-case, it would still likely be best to keep your documentation
    // within the Public/ directory so it is easily understood that the files are made public almost exactly as-is.

    // For the purpose of this example, we serve the documentation
    // directly from where it is generated by the swift-docc-plugin.
    // Additionally, we leverage the --hosting-base-path to show a slightly more complex example, but you don't need to do it this way.
    // If you're just looking to host your DocC documentation, you can generate it without passing in
    // the --hosting-base-path option and remove the property from the initializer.
    let doccMiddleware = DocCMiddleware(app: app, archive: .init(name: "DocCMiddleware", hostingBasePath: "DocCMiddleware"))
    
    // Use the middleware.
    app.middleware.use(doccMiddleware)
}
