name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    uses: bdrelling/workflows/.github/workflows/swift_test_vapor_package.yml@main
    with:
      scheme: DocCMiddleware
